name       : perl-yaml-tiny
version    : '1.74'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/YAML-Tiny-1.74.tar.gz : 7b38ca9f5d3ce24230a6b8bdc1f47f5b2db348e7f7f9666c26f5955636e33d6c
homepage   : https://metacpan.org/pod/YAML::Tiny
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : YAML::Tiny - Read/Write YAML files with as little code as possible
description: |
    YAML::Tiny - Read/Write YAML files with as little code as possible
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
