name       : perl-yaml-tiny
version    : '1.70'
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/YAML-Tiny-1.70.tar.gz : bbce4b52b5eafdb04e3043975a08dbf394d00b7d2c958adb9d03d9f7e9291255
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : YAML::Tiny - Read/Write YAML files with as little code as possible
description: |
    YAML::Tiny - Read/Write YAML files with as little code as possible
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
